package netty.recorder;

import javax.swing.*;
import java.awt.*;

public class RecorderServerForm {
	private JFrame jFrame;
	private JPanel panel;
	private JTextArea textBox;

	RecorderServerForm() {
		jFrame = new JFrame();
		jFrame.setLocation( 500, 400 );
		jFrame.setContentPane( panel );
		jFrame.setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE );
		jFrame.pack();
		jFrame.setVisible( true );
	}

	public void addText( String chat ) {
		String text = textBox.getText();
		text = text + chat + "\n";
		textBox.setText( text );
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panel = new JPanel();
		panel.setLayout( new BorderLayout( 0, 0 ) );
		final JPanel panel1 = new JPanel();
		panel1.setLayout( new com.intellij.uiDesigner.core.GridLayoutManager( 1, 1, new Insets( 0, 10, 0, 0 ), -1, -1 ) );
		panel.add( panel1, BorderLayout.EAST );
		final JPanel panel2 = new JPanel();
		panel2.setLayout( new com.intellij.uiDesigner.core.GridLayoutManager( 1, 1, new Insets( 0, 0, 0, 10 ), -1, -1 ) );
		panel.add( panel2, BorderLayout.WEST );
		final JPanel panel3 = new JPanel();
		panel3.setLayout( new com.intellij.uiDesigner.core.GridLayoutManager( 1, 1, new Insets( 0, 0, 10, 0 ), -1, -1 ) );
		panel.add( panel3, BorderLayout.NORTH );
		final JPanel panel4 = new JPanel();
		panel4.setLayout( new com.intellij.uiDesigner.core.GridLayoutManager( 1, 1, new Insets( 10, 0, 0, 0 ), -1, -1 ) );
		panel.add( panel4, BorderLayout.SOUTH );
		final JPanel panel5 = new JPanel();
		panel5.setLayout( new com.intellij.uiDesigner.core.GridLayoutManager( 1, 1, new Insets( 0, 0, 0, 0 ), -1, -1 ) );
		panel.add( panel5, BorderLayout.CENTER );
		textBox = new JTextArea();
		textBox.setEditable( false );
		panel5.add( textBox, new com.intellij.uiDesigner.core.GridConstraints( 0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension( 500, 500 ), null, 0, false ) );
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel;
	}
}
