package netty.recorder;

import lombok.extern.slf4j.Slf4j;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;

@Slf4j
public class RecorderClientForm {

	private JFrame jFrame;
	private JPanel panel;
	private JTextField textField;
	private JButton sendButton;

	RecorderClientForm() {
		jFrame = new JFrame();
		jFrame.setLocation( 500, 400 );
		jFrame.setContentPane( panel );
		jFrame.setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE );
		jFrame.pack();
		jFrame.setVisible( true );

	}

	public void setButtonAddListener( ActionListener actionListener ) {
		sendButton.addActionListener( actionListener );
	}

	public String getText() {
		return textField.getText();
	}

	public void exit() {
		jFrame.dispatchEvent( new WindowEvent( jFrame, WindowEvent.WINDOW_CLOSING ) );
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panel = new JPanel();
		panel.setLayout( new BorderLayout( 0, 0 ) );
		final JPanel panel1 = new JPanel();
		panel1.setLayout( new com.intellij.uiDesigner.core.GridLayoutManager( 1, 1, new Insets( 0, 0, 0, 10 ), -1, -1 ) );
		panel.add( panel1, BorderLayout.WEST );
		final JPanel panel2 = new JPanel();
		panel2.setLayout( new com.intellij.uiDesigner.core.GridLayoutManager( 1, 1, new Insets( 0, 10, 0, 0 ), -1, -1 ) );
		panel.add( panel2, BorderLayout.EAST );
		final JPanel panel3 = new JPanel();
		panel3.setLayout( new com.intellij.uiDesigner.core.GridLayoutManager( 1, 1, new Insets( 10, 0, 0, 0 ), -1, -1 ) );
		panel.add( panel3, BorderLayout.NORTH );
		final JPanel panel4 = new JPanel();
		panel4.setLayout( new com.intellij.uiDesigner.core.GridLayoutManager( 1, 1, new Insets( 0, 0, 10, 0 ), -1, -1 ) );
		panel.add( panel4, BorderLayout.SOUTH );
		final JPanel panel5 = new JPanel();
		panel5.setLayout( new com.intellij.uiDesigner.core.GridLayoutManager( 2, 1, new Insets( 0, 0, 0, 0 ), -1, -1 ) );
		panel.add( panel5, BorderLayout.CENTER );
		textField = new JTextField();
		panel5.add( textField, new com.intellij.uiDesigner.core.GridConstraints( 0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension( 150, -1 ), null, 0, false ) );
		sendButton = new JButton();
		sendButton.setText( "send" );
		panel5.add( sendButton, new com.intellij.uiDesigner.core.GridConstraints( 1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false ) );
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel;
	}
}
